url=jdbc:postgresql://localhost:5432/meikocn
username=meikocn
password=meikocn
driver=org.postgresql.Driver

#### Reference database properties
referenceUrl=hibernate:spring:com.meikocn.api.model?dialect=org.hibernate.dialect.PostgreSQLDialect